services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: llmops-qdrant
    restart: unless-stopped
    ports:
      - "6323:6333" # this is the default port for Qdrant API
      - "6324:6334" # this is the default port for Qdrant gRPC
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    volumes:
      - qdrant_storage:/qdrant/storage
      - qdrant_config:/qdrant/config

  llmops-s3:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: llmops-s3
    restart: unless-stopped
    ports:
      - "9000:9000" # API
      - "9001:9001" # GUI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${S3_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - S3_data:/data
  
  postgres:
    image: postgres:16
    container_name: llmops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: llmops
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: llmops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  qdrant_storage:
  qdrant_config:
  S3_data:
  postgres_data:
